version: "3.9"
services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    env_file:
      - stack-env.env
    volumes:
      - "./kafka_backup:/bitnami"
    networks:
      - lyi-networks
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "./kafka_backup:/bitnami"
    env_file:
      - stack-env.env
    depends_on:
      - zookeeper
    networks:
      - lyi-networks
  kafka_view:
    image: quay.io/cloudhut/kowl:master
    container_name: kafka_view
    restart: on-failure
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    volumes:
      - ./configs/kowlConfig.yaml:/etc/kowl/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper
    networks:
      - lyi-networks
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      xpack.security.enabled: "false"
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      - lyi-networks
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.8.0
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    networks:
      - lyi-networks
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  couchbase:
    image: couchbase:latest
    networks:
      - lyi-networks
    volumes:
      - ./data:/opt/couchbase/var/lib/couchbase/data
    ports:
      - 8091-8097:8091-8097
  app:
    env_file:
      - stack-env.env
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    networks:
      - lyi-networks
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
      - kibana
networks:
  lyi-networks:
    name: lyi-networks
