version: "3.9"
services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    env_file:
      - stack-env.env
    volumes:
      - "./kafka_backup:/bitnami"
    networks:
      - lyi-networks
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "./kafka_backup:/bitnami"
    env_file:
      - stack-env.env
    depends_on:
      - zookeeper
    networks:
      - lyi-networks
  kafka_view:
    image: quay.io/cloudhut/kowl:master
    container_name: kafka_view
    restart: on-failure
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    volumes:
      - ./configs/kowlConfig.yaml:/etc/kowl/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper
    networks:
      - lyi-networks
  app:
    env_file:
      - stack-env.env
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    networks:
      - lyi-networks
    entrypoint: ["tail", "-f", "/dev/null"]
networks:
  lyi-networks:
    name: lyi-networks
